[package]
name = "implib"
version = "0.1.0"
description = "Generate Windows import library from module definition file"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ar = "0.9.0"
memoffset = "0.6.5"
object = { version = "0.28.4", default-features = false, features = ["archive", "coff", "pe", "write"] }
