[package]
name = "implib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object = { version = "0.28.4", default-features = false, features = ["archive", "coff", "pe", "write"] }
